//! The DSH target — port of the DSH sections of `bin/my-workbench.js`
//! (PLAN.md §3: the plugin itself stays authored JavaScript; only the pure
//! file/JSON operations live here).
//!
//! Installs, at user level under the DSH home (`$DSH_HOME` else `~/.dsh`):
//! the agent preset in `.agent-presets/my-workbench/` (preset.yml byte copy,
//! rendered agent.cordis.yml, the lane-plugin host half with its `{{dep:…}}`
//! placeholders baked to `file:` URLs, the generated roster/prompts modules,
//! and the lane-plugin-ui page), plus exactly ONE managed block row in the
//! chosen profile's `cordis.patch.yml`. Rendering comes from
//! [`crate::render`]; dependency resolution from [`crate::dsh_deps`].

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::dsh_deps;
use crate::error::WorkbenchError;
use crate::render;
use crate::types::{
    DriftFile, DshHomeSource, DshInfo, EngineContext, EventSink, InstallEvent, LaneRecord,
    LogLevel, ModuleOutcome, PlanItem, PlanKind, Selection, Target,
};

// ------------------------------------------------------------------ constants

/// Directory name of the DSH agent preset installed into `<DSH_HOME>/.agent-presets/`.
pub const DSH_PRESET_ID: &str = "my-workbench";

/// Directory the lane plugin occupies inside the installed preset.
pub const DSH_LANE_PLUGIN_DIR: &str = "lane-plugin";

/// Directory the lane settings page occupies inside the installed preset.
pub const DSH_LANE_UI_DIR: &str = "lane-plugin-ui";

/// Profile filenames the DSH target reads or maintains.
pub const PROFILE_ROOT_FILENAME: &str = "cordis.yml";
pub const PROFILE_PATCH_FILENAME: &str = "cordis.patch.yml";

/// Comment fence around the ONE profile row this target owns. Everything
/// between the two lines is regenerated on every run; everything outside them
/// belongs to the user and is never touched.
pub const LANE_UI_BLOCK_BEGIN: &str =
    "# >>> my-workbench lane settings page (managed block - regenerated by `my-workbench --dsh`) >>>";
pub const LANE_UI_BLOCK_END: &str = "# <<< my-workbench lane settings page <<<";

/// `{{dep:<alias>}}` placeholders in the lane plugin's host module — each
/// names a deployment package the plugin imports at runtime and is replaced
/// with an absolute `file:` URL at install time.
pub fn dep_re() -> &'static regex::Regex {
    static DEP_RE: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
    DEP_RE.get_or_init(|| regex::Regex::new(r"\{\{dep:([\w-]+)\}\}").expect("valid DEP_RE"))
}

/// Deployment packages the lane plugin imports, keyed by template alias
/// (`DSH_LANE_PLUGIN_DEPS` in the CLI; exposed so the engine can pass the dep
/// map to [`dsh_deps::resolve_lane_dependencies`]).
pub const DSH_LANE_PLUGIN_DEPS: [(&str, &str); 2] = [
    ("dsh-tools", "@deepseek-ai/dsh-tools"),
    ("schemastery", "@deepseek-ai/schemastery"),
];

/// The dep map in [`DSH_LANE_PLUGIN_DEPS`], as consumed by the resolve fns.
pub fn lane_plugin_dep_map() -> BTreeMap<String, String> {
    DSH_LANE_PLUGIN_DEPS
        .iter()
        .map(|(alias, package)| (alias.to_string(), package.to_string()))
        .collect()
}

/// The preset root inside a DSH home.
pub fn preset_root(home: &Path) -> PathBuf {
    home.join(".agent-presets").join(DSH_PRESET_ID)
}

/// Never copied, no matter where they appear in a source tree (`isSkipped`).
/// Applies to any directory walk over DSH source material; the preset's fixed
/// file set never contains such a name.
pub fn is_skipped(name: &str) -> bool {
    name == "node_modules"
        || name == "package-lock.json"
        || name == "settings.local.json"
        || name.starts_with('.')
}

// ------------------------------------------------------------------- location

/// DSH home: `$DSH_HOME` wins, else `<home>/.dsh` (the layout DSH itself
/// creates). An empty `DSH_HOME` is falsy in the JS and stays the default here.
pub fn dsh_home(home: &Path) -> PathBuf {
    match std::env::var("DSH_HOME") {
        Ok(value) if !value.is_empty() => PathBuf::from(value),
        _ => home.join(".dsh"),
    }
}

/// The DSH lane record is authored once (`agents/backends/dsh/lanes.json`) and
/// rendered for both plugin halves; parse and validate it exactly like
/// `dshLanes()` — key/tool shape, duplicates, per-record completeness — with
/// the same error texts.
pub fn lanes(source_root: &Path) -> Result<Vec<LaneRecord>, WorkbenchError> {
    let path = source_root
        .join("agents")
        .join("backends")
        .join("dsh")
        .join("lanes.json");
    let text = std::fs::read_to_string(&path)?;
    let value: serde_json::Value = serde_json::from_str(&text)?;
    let Some(array) = value.as_array().filter(|array| !array.is_empty()) else {
        return Err(WorkbenchError::Message(
            "agents/backends/dsh/lanes.json must contain lanes".to_owned(),
        ));
    };

    fn is_lane_key(key: &str) -> bool {
        // JS /^[\w-]+$/ with the non-unicode (ASCII) \w class.
        !key.is_empty()
            && key
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
    }

    fn is_lane_tool(tool: &str) -> bool {
        // JS /^subagent_[\w_]+$/
        let rest = match tool.strip_prefix("subagent_") {
            Some(rest) => rest,
            None => return false,
        };
        !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
    }

    let mut keys = std::collections::HashSet::new();
    let mut tools = std::collections::HashSet::new();
    let mut lanes = Vec::with_capacity(array.len());
    for lane in array {
        let key = lane.get("key").and_then(serde_json::Value::as_str).unwrap_or_default();
        let tool = lane.get("tool").and_then(serde_json::Value::as_str).unwrap_or_default();
        let zh = lane.get("zh").and_then(serde_json::Value::as_str);
        let shape_ok = lane.is_object()
            && is_lane_key(key)
            && is_lane_tool(tool)
            && zh.is_some_and(|zh| !zh.trim().is_empty());
        if !shape_ok {
            return Err(WorkbenchError::Message("invalid DSH lane record".to_owned()));
        }
        if !keys.insert(key.to_owned()) || !tools.insert(tool.to_owned()) {
            return Err(WorkbenchError::Message(format!(
                "duplicate DSH lane key or tool: {key}"
            )));
        }
        let recommended = lane.get("recommended");
        let complete = lane.get("denyWrites").is_some_and(serde_json::Value::is_boolean)
            && lane.get("denyShell").is_some_and(serde_json::Value::is_boolean)
            && recommended.is_some_and(serde_json::Value::is_object)
            && ["provider", "model", "reasoningEffort"].iter().all(|field| {
                recommended
                    .and_then(|r| r.get(*field))
                    .is_some_and(serde_json::Value::is_string)
            });
        if !complete {
            return Err(WorkbenchError::Message(format!("incomplete DSH lane: {key}")));
        }
        lanes.push(LaneRecord {
            key: key.to_owned(),
            tool: tool.to_owned(),
            zh: zh.expect("checked above").to_owned(),
            deny_writes: lane
                .get("denyWrites")
                .and_then(serde_json::Value::as_bool)
                .expect("checked above"),
            deny_shell: lane
                .get("denyShell")
                .and_then(serde_json::Value::as_bool)
                .expect("checked above"),
            recommended: serde_json::from_value(
                recommended.expect("checked above").clone(),
            )?,
        });
    }
    Ok(lanes)
}

/// The profile directory whose user patch layer this target maintains, or
/// `None`. `web` wins (the DSH web profile this feature exists for) when it
/// carries `cordis.yml` or `cordis.patch.yml`; a home with exactly one other
/// profile uses it; anything else is left alone and reported.
pub fn find_profile_dir(home: &Path) -> Option<PathBuf> {
    let profiles_dir = home.join("profiles");
    if !profiles_dir.exists() {
        return None;
    }
    let web = profiles_dir.join("web");
    if web.join(PROFILE_PATCH_FILENAME).exists() || web.join(PROFILE_ROOT_FILENAME).exists() {
        return Some(web);
    }
    let mut names = Vec::new();
    for name in sorted_readdir(&profiles_dir) {
        if name == "node_modules" {
            continue;
        }
        let dir = profiles_dir.join(&name);
        match std::fs::metadata(&dir) {
            Ok(meta) if meta.is_dir() => {}
            _ => continue,
        }
        if dir.join(PROFILE_PATCH_FILENAME).exists() || dir.join(PROFILE_ROOT_FILENAME).exists() {
            names.push(name);
        }
    }
    if names.len() == 1 {
        Some(profiles_dir.join(names.remove(0)))
    } else {
        None
    }
}

/// DSH detection for the environment panel: where the home came from,
/// existence, the profile the managed-block row would target, and the number
/// of profile directories under `profiles/` (`node_modules` excluded).
pub fn detect_dsh(home: &Path) -> DshInfo {
    let home_source = match std::env::var("DSH_HOME") {
        Ok(value) if !value.is_empty() => DshHomeSource::Env,
        _ => DshHomeSource::Default,
    };
    let exists = home.exists();
    let profile = find_profile_dir(home)
        .and_then(|dir| dir.file_name().map(|name| name.to_string_lossy().into_owned()));
    let profiles_dir = home.join("profiles");
    let profiles_count = if profiles_dir.exists() {
        sorted_readdir(&profiles_dir)
            .into_iter()
            .filter(|name| name != "node_modules")
            .filter(|name| {
                std::fs::metadata(profiles_dir.join(name))
                    .map(|meta| meta.is_dir())
                    .unwrap_or(false)
            })
            .count()
    } else {
        0
    };
    DshInfo {
        home: home.to_path_buf(),
        home_source,
        exists,
        profile,
        profiles_count,
    }
}

// --------------------------------------------------------------- managed block

/// The managed block text for one profile's patch layer (`laneUiPatchBlock`).
pub fn lane_ui_patch_block(row_name: &str) -> String {
    [
        LANE_UI_BLOCK_BEGIN,
        "# The lane settings page is a PROFILE-layer client plugin: DSH discovers client",
        "# halves by scanning the profile loader's own entries, so a row inside an agent",
        "# preset is never scanned and its page is never served. This single inert row is",
        "# the whole profile-level footprint of the DSH target — no tools, no services,",
        "# and no packages installed. Delete the block to remove the page.",
        "- insert:",
        "    - id: my-workbench-lanes-ui",
        &format!("      name: '{row_name}'"),
        LANE_UI_BLOCK_END,
    ]
    .join("\n")
}

/// What `writeLaneUiPatchRow` would do (or did) to one profile's patch layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PatchOutcome {
    /// The rebuilt text is byte-identical to the file — nothing to write.
    Unchanged,
    /// The block was appended (or the file created).
    Added,
    /// The block was replaced in place.
    Updated,
    /// The file is not a shape this target may touch — NEVER written.
    Skipped,
}

/// Compute the managed-block outcome for one profile without writing
/// (`writeLaneUiPatchRow` up to the write): the outcome plus the rebuilt text
/// for a writable outcome (`None` for [`PatchOutcome::Unchanged`] /
/// [`PatchOutcome::Skipped`]).
///
/// Classification: a byte-identical rebuilt block means unchanged; an opening
/// marker without its closing marker is a hard error; a flow empty list `[]`
/// has those lines removed before the block is joined on; empty,
/// comment-only, `---`-only and plain block-sequence files get the block
/// appended with a `""` / `"\n"` / `"\n\n"` separator; "meaningful" ignores
/// only `^\s*#` and `^\s*---\s*$` lines; any other shape is skipped.
pub fn compute_lane_ui_patch_row(
    profile_dir: &Path,
    row_name: &str,
) -> Result<(PatchOutcome, Option<String>), WorkbenchError> {
    let file = profile_dir.join(PROFILE_PATCH_FILENAME);
    let block = lane_ui_patch_block(row_name);
    let existing = match std::fs::read_to_string(&file) {
        Ok(text) => Some(text),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => None,
        Err(err) => return Err(err.into()),
    };
    let begin = existing.as_deref().and_then(|text| text.find(LANE_UI_BLOCK_BEGIN));

    let (outcome, next) = if let Some(begin) = begin {
        let existing = existing.expect("begin implies existing");
        let end = match existing[begin..].find(LANE_UI_BLOCK_END) {
            Some(offset) => begin + offset,
            None => {
                return Err(WorkbenchError::Message(format!(
                    "{} has the managed block's opening marker but not its closing marker; \
                     fix or delete the block, then re-run",
                    file.display()
                )))
            }
        };
        let after = end + LANE_UI_BLOCK_END.len();
        let next = format!(
            "{}{}{}",
            &existing[..begin],
            block,
            &existing[after..]
        );
        let outcome = if next == existing {
            PatchOutcome::Unchanged
        } else {
            PatchOutcome::Updated
        };
        (outcome, next)
    } else if existing.is_none() {
        (PatchOutcome::Added, format!("{block}\n"))
    } else {
        let existing = existing.expect("begin None and file exists");
        let meaningful = existing
            .split('\n')
            .filter(|line| !is_comment_line(line) && !is_document_marker(line))
            .collect::<Vec<_>>()
            .join("\n")
            .trim()
            .to_owned();
        if meaningful == "[]" {
            let without_empty_list = existing
                .split('\n')
                .filter(|line| line.trim() != "[]")
                .collect::<Vec<_>>()
                .join("\n");
            let separator = if without_empty_list.trim().is_empty()
                || without_empty_list.ends_with("\n\n")
            {
                ""
            } else if without_empty_list.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            (
                PatchOutcome::Added,
                format!("{without_empty_list}{separator}{block}\n"),
            )
        } else if meaningful.is_empty() || meaningful.starts_with('-') {
            let separator = if existing.is_empty() || existing.ends_with("\n\n") {
                ""
            } else if existing.ends_with('\n') {
                "\n"
            } else {
                "\n\n"
            };
            (PatchOutcome::Added, format!("{existing}{separator}{block}\n"))
        } else {
            (PatchOutcome::Skipped, String::new())
        }
    };

    let next = match outcome {
        PatchOutcome::Unchanged | PatchOutcome::Skipped => None,
        _ => Some(next),
    };
    Ok((outcome, next))
}

/// Apply the computed outcome to one profile's patch layer.
fn write_lane_ui_patch_row(
    profile_dir: &Path,
    row_name: &str,
) -> Result<PatchOutcome, WorkbenchError> {
    let (outcome, next) = compute_lane_ui_patch_row(profile_dir, row_name)?;
    if let Some(text) = next {
        std::fs::create_dir_all(profile_dir)?;
        std::fs::write(profile_dir.join(PROFILE_PATCH_FILENAME), text)?;
    }
    Ok(outcome)
}

/// JS `/^\s*#/` — a line whose first non-whitespace character is `#`.
fn is_comment_line(line: &str) -> bool {
    line.trim_start().starts_with('#')
}

/// JS `/^\s*---\s*$/` — a line that is exactly a YAML document marker.
fn is_document_marker(line: &str) -> bool {
    line.trim() == "---"
}

fn sorted_readdir(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = match std::fs::read_dir(dir) {
        Ok(entries) => entries
            .filter_map(|entry| entry.ok().and_then(|e| e.file_name().into_string().ok()))
            .collect(),
        Err(_) => return Vec::new(),
    };
    names.sort();
    names
}

// ------------------------------------------------------------------ file set

/// One file the DSH install writes, in CLI apply order.
enum DshOutput {
    /// Byte copy from a path relative to the source root.
    Copy {
        dest_rel: &'static str,
        source_rel: String,
        from: PathBuf,
    },
    /// Rendered text.
    Rendered {
        dest_rel: &'static str,
        source_rel: String,
        text: String,
    },
}

impl DshOutput {
    fn dest_rel(&self) -> &'static str {
        match self {
            DshOutput::Copy { dest_rel, .. } | DshOutput::Rendered { dest_rel, .. } => dest_rel,
        }
    }

    fn source_rel(&self) -> &str {
        match self {
            DshOutput::Copy { source_rel, .. } | DshOutput::Rendered { source_rel, .. } => {
                source_rel
            }
        }
    }

    /// The bytes an install writes for this output — the copy source's bytes
    /// (`fs::copy`'s read side) or the rendered text. Shared by
    /// [`execute_dsh_in`]'s writes and [`drift_dsh_with_compared`]'s
    /// byte-compare so both sides of "installed vs would-be-installed" come
    /// from one place.
    fn content_bytes(&self) -> std::io::Result<Vec<u8>> {
        match self {
            DshOutput::Copy { from, .. } => std::fs::read(from),
            DshOutput::Rendered { text, .. } => Ok(text.clone().into_bytes()),
        }
    }
}

/// The full preset file set, rendered (`installLanePlugin` + `installLaneUiPlugin`
/// + the two top files of `applyDsh`). Rendering runs here even in plan mode so
/// a broken source fails before any write, exactly like the CLI flow.
fn dsh_outputs(
    source_root: &Path,
    lanes: &[LaneRecord],
    resolved_deps: &BTreeMap<String, String>,
) -> Result<Vec<DshOutput>, WorkbenchError> {
    fn source_rel(rel: &str) -> String {
        rel.to_owned()
    }

    let dsh_src = source_root.join("agents").join("backends").join("dsh");
    Ok(vec![
        DshOutput::Copy {
            dest_rel: "preset.yml",
            source_rel: source_rel("agents/backends/dsh/preset.yml"),
            from: dsh_src.join("preset.yml"),
        },
        DshOutput::Rendered {
            dest_rel: "agent.cordis.yml",
            source_rel: source_rel("agents/backends/dsh/agent.cordis.yml"),
            text: render::render_dsh_composition(source_root)?,
        },
        DshOutput::Copy {
            dest_rel: "lane-plugin/package.json",
            source_rel: source_rel("agents/backends/dsh/lane-plugin/host-package/package.json"),
            from: dsh_src
                .join("lane-plugin")
                .join("host-package")
                .join("package.json"),
        },
        DshOutput::Rendered {
            dest_rel: "lane-plugin/src/index.js",
            source_rel: source_rel("agents/backends/dsh/lane-plugin/host-package/src/index.js"),
            text: render::render_lane_host(source_root, resolved_deps)?,
        },
        DshOutput::Rendered {
            dest_rel: "lane-plugin/src/roster.generated.js",
            source_rel: source_rel("agents/backends/dsh/lane-plugin/src/roster.generated.js"),
            text: render::lane_roster_source(lanes),
        },
        DshOutput::Rendered {
            dest_rel: "lane-plugin/src/prompts.generated.js",
            source_rel: source_rel("agents/backends/dsh/lane-plugin/src/prompts.generated.js"),
            text: render::render_lane_prompts(source_root, lanes)?,
        },
        DshOutput::Copy {
            dest_rel: "lane-plugin-ui/package.json",
            source_rel: source_rel("agents/backends/dsh/lane-plugin-ui/package.json"),
            from: dsh_src.join("lane-plugin-ui").join("package.json"),
        },
        DshOutput::Copy {
            dest_rel: "lane-plugin-ui/src/index.js",
            source_rel: source_rel("agents/backends/dsh/lane-plugin-ui/src/index.js"),
            from: dsh_src.join("lane-plugin-ui").join("src").join("index.js"),
        },
        DshOutput::Rendered {
            dest_rel: "lane-plugin-ui/lib/client.js",
            source_rel: source_rel("agents/backends/dsh/lane-plugin-ui/lib/client.js"),
            text: render::lane_ui_client_source(source_root, lanes)?,
        },
    ])
}

/// The `file:` URL naming the installed lane UI host half — the profile row's
/// `name` (`rowName` in `applyDsh`). The literal join, never canonicalized,
/// matching the JS `pathToFileURL(join(...)).href`.
fn lane_ui_row_name(preset_root: &Path) -> String {
    dsh_deps::path_to_file_url(&preset_root.join(DSH_LANE_UI_DIR).join("src").join("index.js"))
}

// ---------------------------------------------------------------- display

/// True when the DSH home sits inside the user home, so destinations display
/// as `~/…` (the CLI's `userLevel` display decision).
fn home_is_user_level(home: &Path, user_home: &Path) -> bool {
    home.starts_with(user_home)
}

/// Display path: `~/…` relative to the user home for a user-level DSH home,
/// the absolute path otherwise.
fn display_path(path: &Path, user_home: &Path, user_level: bool) -> String {
    if user_level {
        if let Ok(relative) = path.strip_prefix(user_home) {
            return format!("~/{}", relative.to_string_lossy().replace('\\', "/"));
        }
    }
    path.to_string_lossy().into_owned()
}

fn log(sink: &dyn EventSink, level: LogLevel, text: impl Into<String>) {
    let time_ms = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|since| since.as_millis() as u64)
        .unwrap_or(0);
    sink.emit(InstallEvent::Log {
        time_ms,
        target: Some(Target::Dsh),
        level,
        text: text.into(),
    });
}

// ----------------------------------------------------------------------- plan

/// DSH plan: zero writes; per-file Create/Skip/Overwrite items under the
/// preset root plus one `ManagedBlock` item when the patch row would be added
/// or updated (an unchanged or skipped row becomes notes). Dependency
/// resolution happened upstream — `resolved_deps` is the alias → `file:` URL
/// map [`dsh_deps::resolve_lane_dependencies`] produced.
pub fn plan_dsh(
    source_root: &Path,
    ctx: &EngineContext,
    sel: &Selection,
    resolved_deps: &BTreeMap<String, String>,
) -> Result<ModuleOutcome, WorkbenchError> {
    let home = dsh_home(&ctx.home);
    plan_dsh_in(source_root, sel, resolved_deps, &home)
}

/// Parameter-injected variant of [`plan_dsh`] (the DSH home supplied by the
/// caller instead of `$DSH_HOME`).
pub fn plan_dsh_in(
    source_root: &Path,
    sel: &Selection,
    resolved_deps: &BTreeMap<String, String>,
    home: &Path,
) -> Result<ModuleOutcome, WorkbenchError> {
    let lanes = lanes(source_root)?;
    let outputs = dsh_outputs(source_root, &lanes, resolved_deps)?;
    let preset = preset_root(home);

    let mut outcome = ModuleOutcome::default();
    for output in &outputs {
        let dest = preset.join(output.dest_rel());
        let exists = dest.exists();
        let kind = if exists && !sel.force {
            PlanKind::Skip
        } else if exists {
            PlanKind::Overwrite
        } else {
            PlanKind::Create
        };
        match kind {
            PlanKind::Create => outcome.created += 1,
            PlanKind::Skip => outcome.skipped += 1,
            PlanKind::Overwrite => outcome.overwritten += 1,
            PlanKind::ManagedBlock => unreachable!("file items are never ManagedBlock"),
        }
        outcome.items.push(PlanItem {
            target: Target::Dsh,
            path: dest,
            source_rel: output.source_rel().to_owned(),
            kind,
        });
    }

    let row_name = lane_ui_row_name(&preset);
    match find_profile_dir(home) {
        None => {
            outcome.notes.push(format!(
                "未在 {} 下找到唯一 profile 目录，设置页未写入",
                home.join("profiles").display()
            ));
            outcome.notes.push(manual_row_note(
                &format!("你的 profile 的 {PROFILE_PATCH_FILENAME}"),
                &row_name,
            ));
        }
        Some(profile_dir) => {
            let (result, _) = compute_lane_ui_patch_row(&profile_dir, &row_name)?;
            match result {
                PatchOutcome::Unchanged => {
                    outcome
                        .notes
                        .push("受管块已是最新，无需更改".to_owned());
                }
                PatchOutcome::Skipped => {
                    outcome.notes.push(format!(
                        "{} 不是纯补丁列表，受管行未写入（直接追加会破坏该文件）",
                        profile_dir.join(PROFILE_PATCH_FILENAME).display()
                    ));
                    outcome
                        .notes
                        .push(manual_row_note("该文件", &row_name));
                }
                PatchOutcome::Added | PatchOutcome::Updated => {
                    outcome.managed_blocks += 1;
                    outcome.items.push(PlanItem {
                        target: Target::Dsh,
                        path: profile_dir.join(PROFILE_PATCH_FILENAME),
                        source_rel: profile_source_rel(home, &profile_dir),
                        kind: PlanKind::ManagedBlock,
                    });
                }
            }
        }
    }
    outcome
        .notes
        .push("DSH 在会话启动时读取预设：请打开新会话并选择该预设".to_owned());
    Ok(outcome)
}

/// The manual-row instructions for a profile the target could not mount
/// (`applyDsh`'s skip notes, collapsed into one note).
fn manual_row_note(where_phrase: &str, row_name: &str) -> String {
    format!(
        "请在 {where_phrase} 中手动加入以下行以启用该页面：\n  - insert:\n      - id: \
         my-workbench-lanes-ui\n        name: '{row_name}'"
    )
}

fn profile_source_rel(home: &Path, profile_dir: &Path) -> String {
    let fallback = profile_dir
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default();
    let relative = profile_dir
        .strip_prefix(home)
        .map(|relative| relative.to_string_lossy().replace('\\', "/"))
        .unwrap_or(fallback);
    format!("{relative}/{PROFILE_PATCH_FILENAME}")
}

// ------------------------------------------------------------------- execute

/// DSH execute: resolves the plugin's two deployment imports BEFORE the first
/// write (a DSH home that cannot supply them fails with nothing
/// half-installed), then writes the preset file set with log events and
/// cooperative cancellation between files, and finally maintains the single
/// profile patch row.
pub fn execute_dsh(
    source_root: &Path,
    ctx: &EngineContext,
    sel: &Selection,
    sink: &dyn EventSink,
) -> Result<ModuleOutcome, WorkbenchError> {
    let home = dsh_home(&ctx.home);
    let path_env = std::env::var("PATH").unwrap_or_default();
    let env_modules = std::env::var("MY_WORKBENCH_DSH_NODE_MODULES")
        .ok()
        .filter(|value| !value.is_empty());
    execute_dsh_in(
        source_root,
        ctx,
        sel,
        sink,
        &home,
        &path_env,
        env_modules.as_deref().map(Path::new),
    )
}

/// Parameter-injected variant of [`execute_dsh`] (home / `PATH` /
/// `MY_WORKBENCH_DSH_NODE_MODULES` supplied by the caller).
pub fn execute_dsh_in(
    source_root: &Path,
    ctx: &EngineContext,
    sel: &Selection,
    sink: &dyn EventSink,
    home: &Path,
    path_env: &str,
    env_modules: Option<&Path>,
) -> Result<ModuleOutcome, WorkbenchError> {
    // Resolve the plugin's two deployment imports BEFORE the first write: a DSH
    // home that cannot supply them must fail with nothing half-installed.
    let specifiers = dsh_deps::resolve_lane_dependencies_in(
        home,
        &lane_plugin_dep_map(),
        path_env,
        env_modules,
    )?;
    let lanes = lanes(source_root)?;
    let outputs = dsh_outputs(source_root, &lanes, &specifiers)?;
    let preset = preset_root(home);
    let user_level = home_is_user_level(home, &ctx.home);

    let shown = display_path(&preset, &ctx.home, user_level);
    log(
        sink,
        LogLevel::Info,
        format!("{shown}/（用户级：preset.yml、agent.cordis.yml、lane-plugin/、lane-plugin-ui/）"),
    );

    let mut outcome = ModuleOutcome::default();
    for output in &outputs {
        if sink.is_cancelled() {
            return Ok(outcome);
        }
        let dest_rel = output.dest_rel();
        if dest_rel == "lane-plugin/package.json" {
            log(
                sink,
                LogLevel::Info,
                format!("{DSH_LANE_PLUGIN_DIR}/（宿主插件与 {} 个专项提示词）", lanes.len()),
            );
        } else if dest_rel == "lane-plugin-ui/package.json" {
            log(
                sink,
                LogLevel::Info,
                format!("{DSH_LANE_UI_DIR}/（设置页）"),
            );
        }
        let dest = preset.join(dest_rel);
        let shown = display_path(&dest, &ctx.home, user_level);
        let exists = dest.exists();
        if exists && !sel.force {
            outcome.skipped += 1;
            log(sink, LogLevel::Info, format!("跳过 {shown}（已存在）"));
            continue;
        }
        match output {
            DshOutput::Copy { from, .. } => {
                std::fs::create_dir_all(dest.parent().expect("dest has a parent"))?;
                std::fs::copy(from, &dest)?;
            }
            DshOutput::Rendered { text, .. } => {
                std::fs::create_dir_all(dest.parent().expect("dest has a parent"))?;
                std::fs::write(&dest, text)?;
            }
        }
        if exists {
            outcome.overwritten += 1;
        } else {
            outcome.created += 1;
        }
        log(
            sink,
            LogLevel::Info,
            format!("{} {shown}", if exists { "覆盖" } else { "新建" }),
        );
    }

    if sink.is_cancelled() {
        return Ok(outcome);
    }

    // The settings page is a CLIENT plugin, and dsh-client-modules only scans
    // the profile loader's own entries — a row inside an agent preset is never
    // seen. One profile row is therefore the minimum footprint, and it is the
    // whole of it.
    let row_name = lane_ui_row_name(&preset);
    match find_profile_dir(home) {
        None => {
            log(
                sink,
                LogLevel::Info,
                format!(
                    "未在 {} 下找到唯一 profile 目录，设置页未写入",
                    home.join("profiles").display()
                ),
            );
            log(
                sink,
                LogLevel::Info,
                manual_row_note(
                    &format!("你的 profile 的 {PROFILE_PATCH_FILENAME}"),
                    &row_name,
                ),
            );
        }
        Some(profile_dir) => {
            let patch_file = profile_dir.join(PROFILE_PATCH_FILENAME);
            let patch_existed = patch_file.exists();
            let shown = display_path(
                &patch_file,
                &ctx.home,
                user_level,
            );
            match write_lane_ui_patch_row(&profile_dir, &row_name)? {
                PatchOutcome::Skipped => {
                    log(
                        sink,
                        LogLevel::Warn,
                        format!(
                            "警告：{shown} 不是纯补丁列表，受管行未写入（直接追加会破坏该文件）"
                        ),
                    );
                    log(sink, LogLevel::Info, manual_row_note("该文件", &row_name));
                }
                PatchOutcome::Unchanged => {
                    log(sink, LogLevel::Info, format!("跳过 {shown}（已是最新）"));
                    log(
                        sink,
                        LogLevel::Info,
                        "仅写入一条静态 UI 行；不安装任何工具或软件包",
                    );
                    log(
                        sink,
                        LogLevel::Info,
                        "受管块已是最新，无需更改",
                    );
                }
                PatchOutcome::Added => {
                    outcome.managed_blocks += 1;
                    let label = if patch_existed { "追加" } else { "新建" };
                    log(sink, LogLevel::Info, format!("{label} {shown}"));
                    log(
                        sink,
                        LogLevel::Info,
                        "仅写入一条静态 UI 行；不安装任何工具或软件包",
                    );
                }
                PatchOutcome::Updated => {
                    outcome.managed_blocks += 1;
                    log(sink, LogLevel::Info, format!("覆盖 {shown}"));
                    log(
                        sink,
                        LogLevel::Info,
                        "仅写入一条静态 UI 行；不安装任何工具或软件包",
                    );
                }
            }
        }
    }
    log(
        sink,
        LogLevel::Info,
        "DSH 在会话启动时读取预设：请打开新会话并选择该预设",
    );
    Ok(outcome)
}

// --------------------------------------------------------------------- drift

/// Stable display marker for the managed profile row's drift entry. The patch
/// layer is user-owned and copied from nowhere, so [`DriftFile::source_rel`]
/// has no source-relative origin to name and types.rs has no better field; a
/// fixed marker keeps the GUI display stable across profile names.
const MANAGED_PATCH_DRIFT_REL: &str = "cordis.patch.yml (managed block)";

/// Byte-compare what a DSH install WOULD write against what is on disk: the
/// nine preset files through the same render/copy set [`plan_dsh_in`] and
/// [`execute_dsh_in`] install, plus the single managed profile row. See
/// [`drift_dsh_with_compared`] for the exact semantics.
pub fn drift_dsh(
    source_root: &Path,
    home: &Path,
    force: bool,
) -> Result<Vec<DriftFile>, WorkbenchError> {
    drift_dsh_with_compared(source_root, home, force).map(|(drifted, _)| drifted)
}

/// [`drift_dsh`] plus the number of files the comparison examined, so the
/// engine can count DSH into `Tier1Report.compared` without knowing the
/// preset file set itself.
///
/// Semantics (`assemble --check` drift applied to an installed preset): a
/// preset file that exists on disk is compared byte-for-byte against
/// [`DshOutput::content_bytes`] and reported when it differs; one that is not
/// installed is not compared. The managed row is compared through
/// [`compute_lane_ui_patch_row`]: an unchanged block is not drift, a shape the
/// install refuses to touch writes nothing and therefore is not drift either,
/// and a block the install would add or rewrite is ONE drift entry attributed
/// to the patch file — even when the patch file does not exist yet, since the
/// row is the install's only profile-layer footprint and its absence is
/// exactly what a rerun repairs. `force` is accepted but deliberately
/// ignored: drift is a content difference regardless of the overwrite flag.
pub fn drift_dsh_with_compared(
    source_root: &Path,
    home: &Path,
    force: bool,
) -> Result<(Vec<DriftFile>, usize), WorkbenchError> {
    let _ = force; // drift detection is force-independent (see doc above)
    let lanes = lanes(source_root)?;
    let resolved = dsh_deps::resolve_lane_dependencies(home, &lane_plugin_dep_map())?;
    let outputs = dsh_outputs(source_root, &lanes, &resolved)?;
    let preset = preset_root(home);

    let mut drifted = Vec::new();
    let mut compared = 0usize;
    for output in &outputs {
        let dest = preset.join(output.dest_rel());
        let Ok(on_disk) = std::fs::read(&dest) else {
            continue; // not installed → nothing to compare
        };
        compared += 1;
        if on_disk != output.content_bytes()? {
            drifted.push(DriftFile {
                path: dest,
                source_rel: output.source_rel().to_owned(),
                target: Target::Dsh,
            });
        }
    }

    if let Some(profile_dir) = find_profile_dir(home) {
        let row_name = lane_ui_row_name(&preset);
        let (outcome, _) = compute_lane_ui_patch_row(&profile_dir, &row_name)?;
        compared += 1;
        if matches!(outcome, PatchOutcome::Added | PatchOutcome::Updated) {
            drifted.push(DriftFile {
                path: profile_dir.join(PROFILE_PATCH_FILENAME),
                source_rel: MANAGED_PATCH_DRIFT_REL.to_owned(),
                target: Target::Dsh,
            });
        }
    }
    Ok((drifted, compared))
}

// --------------------------------------------------------------------- tests

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
    use std::sync::Mutex;

    fn repo_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(2)
            .expect("crate sits two levels under the repo root")
            .to_path_buf()
    }

    fn lane_record(key: &str, tool: &str) -> serde_json::Value {
        json!({
            "key": key,
            "tool": tool,
            "zh": "测试",
            "denyWrites": true,
            "denyShell": false,
            "recommended": {
                "provider": "deepseek-official",
                "model": "deepseek-v4-pro",
                "reasoningEffort": "high"
            }
        })
    }

    fn write_lanes_file(source_root: &Path, value: &serde_json::Value) {
        let dir = source_root.join("agents").join("backends").join("dsh");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("lanes.json"), value.to_string()).unwrap();
    }

    fn selection(force: bool) -> Selection {
        Selection {
            source: crate::types::Source::Bundled,
            // Inert here: DSH is user-level-only, so nothing reads the
            // Selection's project directory on this path.
            project_dir: std::path::PathBuf::new(),
            targets: vec![Target::Dsh],
            user_level: true,
            force,
        }
    }

    fn engine_context(user_home: &Path) -> EngineContext {
        EngineContext {
            project_dir: user_home.parent().unwrap().to_path_buf(),
            home: user_home.to_path_buf(),
            bundled_root: user_home.to_path_buf(),
            version: crate::VERSION.to_owned(),
        }
    }

    #[derive(Default)]
    struct VecSink {
        events: Mutex<Vec<InstallEvent>>,
    }

    impl EventSink for VecSink {
        fn emit(&self, event: InstallEvent) {
            self.events.lock().unwrap().push(event);
        }
    }

    impl VecSink {
        fn log_texts(&self) -> Vec<String> {
            self.events
                .lock()
                .unwrap()
                .iter()
                .filter_map(|event| match event {
                    InstallEvent::Log { text, .. } => Some(text.clone()),
                    _ => None,
                })
                .collect()
        }
    }

    /// Cancels itself once `after_emits` events have been emitted.
    struct CancelAfterSink {
        after_emits: usize,
        emits: AtomicUsize,
        cancelled: AtomicBool,
    }

    impl CancelAfterSink {
        fn new(after_emits: usize) -> Self {
            Self {
                after_emits,
                emits: AtomicUsize::new(0),
                cancelled: AtomicBool::new(false),
            }
        }
    }

    impl EventSink for CancelAfterSink {
        fn emit(&self, _event: InstallEvent) {
            if self.emits.fetch_add(1, Ordering::SeqCst) + 1 >= self.after_emits {
                self.cancelled.store(true, Ordering::SeqCst);
            }
        }

        fn is_cancelled(&self) -> bool {
            self.cancelled.load(Ordering::SeqCst)
        }
    }

    /// A minimal deployment package, mirroring the JS test helper `packageAt`.
    fn package_at(root: &Path, name: &str, exports_field: &serde_json::Value) {
        let dir = root.join(name);
        std::fs::create_dir_all(&dir).unwrap();
        let manifest = json!({ "version": "1.0.0", "exports": exports_field });
        std::fs::write(dir.join("package.json"), manifest.to_string()).unwrap();
        let entry = match exports_field {
            serde_json::Value::String(entry) => entry.clone(),
            other => other
                .get("import")
                .and_then(serde_json::Value::as_str)
                .expect("test exports carry an import condition")
                .to_owned(),
        };
        let file = dir.join(&entry);
        std::fs::create_dir_all(file.parent().unwrap()).unwrap();
        std::fs::write(&file, "export default {}\n").unwrap();
    }

    /// Fake DSH home whose profile closure carries both deployment packages —
    /// the first search root, so resolution never depends on the machine PATH.
    fn fake_home_with_packages(dir: &Path) -> PathBuf {
        let home = dir.join("dsh-home");
        let modules = home.join("profiles").join("node_modules");
        package_at(&modules, "@deepseek-ai/dsh-tools", &json!("./index.mjs"));
        package_at(
            &modules,
            "@deepseek-ai/schemastery",
            &json!({ "require": "./index.cjs", "import": "./index.mjs" }),
        );
        home
    }

    // -- dsh_home --------------------------------------------------------------

    #[test]
    fn dsh_home_defaults_to_dot_dsh_under_the_given_home() {
        // Only meaningful when the ambient environment does not set DSH_HOME;
        // the parameterized shape is what tests rely on either way.
        if std::env::var("DSH_HOME").is_ok_and(|value| !value.is_empty()) {
            return;
        }
        let user_home = Path::new("/users/example");
        assert_eq!(dsh_home(user_home), PathBuf::from("/users/example/.dsh"));
    }

    // -- lanes() ----------------------------------------------------------------

    #[test]
    fn lanes_parses_and_validates_an_authored_file() {
        let dir = tempfile::tempdir().unwrap();
        write_lanes_file(
            dir.path(),
            &json!([lane_record("explorer", "subagent_explorer"), {
                "key": "librarian",
                "tool": "subagent_librarian",
                "zh": "外部文档研究",
                "denyWrites": true,
                "denyShell": true,
                "recommended": {
                    "provider": "deepseek-official",
                    "model": "deepseek-v4-flash",
                    "reasoningEffort": "low"
                }
            }]),
        );
        let lanes = lanes(dir.path()).unwrap();
        assert_eq!(lanes.len(), 2);
        assert_eq!(lanes[0].key, "explorer");
        assert_eq!(lanes[0].tool, "subagent_explorer");
        assert!(lanes[0].deny_writes);
        assert!(!lanes[0].deny_shell);
        assert_eq!(lanes[1].recommended.reasoning_effort, "low");
    }

    #[test]
    fn lanes_rejects_non_arrays_and_empty_arrays() {
        let dir = tempfile::tempdir().unwrap();
        for value in [json!({}), json!([])] {
            write_lanes_file(dir.path(), &value);
            let error = lanes(dir.path()).unwrap_err().to_string();
            assert_eq!(error, "agents/backends/dsh/lanes.json must contain lanes");
        }
    }

    #[test]
    fn lanes_rejects_invalid_records() {
        let dir = tempfile::tempdir().unwrap();
        let cases = vec![
            json!([json!(null)]),
            json!([json!("explorer")]),
            json!([lane_record("bad key", "subagent_x")]),
            json!([lane_record("", "subagent_x")]),
            json!([lane_record("k", "agent_x")]),
            json!([lane_record("k", "subagent_")]),
            {
                let mut lane = lane_record("k", "subagent_x");
                lane["zh"] = json!(42);
                json!([lane])
            },
            {
                let mut lane = lane_record("k", "subagent_x");
                lane["zh"] = json!("   ");
                json!([lane])
            },
        ];
        for value in cases {
            write_lanes_file(dir.path(), &value);
            assert_eq!(lanes(dir.path()).unwrap_err().to_string(), "invalid DSH lane record");
        }
    }

    #[test]
    fn lanes_rejects_duplicate_keys_and_tools() {
        let dir = tempfile::tempdir().unwrap();
        write_lanes_file(
            dir.path(),
            &json!([lane_record("k", "subagent_a"), lane_record("k", "subagent_b")]),
        );
        assert_eq!(
            lanes(dir.path()).unwrap_err().to_string(),
            "duplicate DSH lane key or tool: k"
        );

        write_lanes_file(
            dir.path(),
            &json!([lane_record("a", "subagent_x"), lane_record("b", "subagent_x")]),
        );
        assert_eq!(
            lanes(dir.path()).unwrap_err().to_string(),
            "duplicate DSH lane key or tool: b"
        );
    }

    #[test]
    fn lanes_rejects_incomplete_records() {
        let dir = tempfile::tempdir().unwrap();
        let cases = vec![
            {
                let mut lane = lane_record("k", "subagent_x");
                lane["denyWrites"] = json!("yes");
                json!([lane])
            },
            {
                let mut lane = lane_record("k", "subagent_x");
                lane.as_object_mut().unwrap().remove("denyShell");
                json!([lane])
            },
            {
                let mut lane = lane_record("k", "subagent_x");
                lane.as_object_mut().unwrap().remove("recommended");
                json!([lane])
            },
            {
                let mut lane = lane_record("k", "subagent_x");
                lane["recommended"] = json!(null);
                json!([lane])
            },
            {
                let mut lane = lane_record("k", "subagent_x");
                lane["recommended"]["model"] = json!(7);
                json!([lane])
            },
        ];
        for value in cases {
            write_lanes_file(dir.path(), &value);
            assert_eq!(
                lanes(dir.path()).unwrap_err().to_string(),
                "incomplete DSH lane: k"
            );
        }
    }

    #[test]
    fn lanes_holds_for_the_real_repo_source() {
        let root = repo_root();
        let lanes = lanes(&root).expect("the repo's authored lanes.json is valid");
        assert!(lanes.len() >= 7, "the repo currently authors 7 lanes");
    }

    // -- find_profile_dir ---------------------------------------------------------

    #[test]
    fn find_profile_dir_prefers_web_then_exactly_one_then_none() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path().join("home");

        // No profiles directory at all.
        assert_eq!(find_profile_dir(&home), None);

        // Empty profiles directory.
        std::fs::create_dir_all(home.join("profiles")).unwrap();
        assert_eq!(find_profile_dir(&home), None);

        // Profiles without either profile file.
        std::fs::create_dir_all(home.join("profiles").join("alpha")).unwrap();
        std::fs::create_dir_all(home.join("profiles").join("beta")).unwrap();
        assert_eq!(find_profile_dir(&home), None);

        // Exactly one non-web profile carrying cordis.yml.
        std::fs::write(home.join("profiles").join("alpha").join("cordis.yml"), "x: 1").unwrap();
        assert_eq!(
            find_profile_dir(&home),
            Some(home.join("profiles").join("alpha"))
        );

        // web wins over everything the moment it carries a profile file.
        std::fs::create_dir_all(home.join("profiles").join("web")).unwrap();
        std::fs::write(home.join("profiles").join("web").join("cordis.patch.yml"), "").unwrap();
        assert_eq!(find_profile_dir(&home), Some(home.join("profiles").join("web")));

        // Multiple non-web candidates stay untouched.
        std::fs::remove_dir_all(home.join("profiles").join("web")).unwrap();
        std::fs::write(home.join("profiles").join("beta").join("cordis.patch.yml"), "").unwrap();
        assert_eq!(find_profile_dir(&home), None);

        // node_modules and loose files are never candidates.
        std::fs::create_dir_all(home.join("profiles").join("node_modules").join("pkg")).unwrap();
        std::fs::write(home.join("profiles").join("loose"), "").unwrap();
        assert_eq!(find_profile_dir(&home), None);
    }

    // -- detect_dsh -----------------------------------------------------------------

    #[test]
    fn detect_dsh_reports_existence_profile_and_count() {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path().join("dsh-home");
        std::fs::create_dir_all(home.join("profiles").join("web")).unwrap();
        std::fs::write(home.join("profiles").join("web").join("cordis.patch.yml"), "").unwrap();
        std::fs::create_dir_all(home.join("profiles").join("cli")).unwrap();
        std::fs::write(home.join("profiles").join("cli").join("cordis.yml"), "").unwrap();
        std::fs::create_dir_all(home.join("profiles").join("node_modules")).unwrap();

        let info = detect_dsh(&home);
        assert!(info.exists);
        assert_eq!(info.profile.as_deref(), Some("web"));
        assert_eq!(info.profiles_count, 2, "node_modules is not a profile");
        let expected_source = match std::env::var("DSH_HOME") {
            Ok(value) if !value.is_empty() => DshHomeSource::Env,
            _ => DshHomeSource::Default,
        };
        assert_eq!(info.home_source, expected_source);

        let absent = detect_dsh(&dir.path().join("absent"));
        assert!(!absent.exists);
        assert_eq!(absent.profile, None);
        assert_eq!(absent.profiles_count, 0);
    }

    // -- the managed block ---------------------------------------------------------

    const OLD_ROW: &str =
        "file:///C:/old/.agent-presets/my-workbench/lane-plugin-ui/src/index.js";
    const NEW_ROW: &str =
        "file:///C:/home/.agent-presets/my-workbench/lane-plugin-ui/src/index.js";

    #[test]
    fn patch_row_reports_unchanged_for_a_byte_identical_block() {
        let dir = tempfile::tempdir().unwrap();
        let profile = dir.path().join("web");
        std::fs::create_dir_all(&profile).unwrap();
        let file = profile.join(PROFILE_PATCH_FILENAME);
        std::fs::write(&file, format!("# mine\n{}\n# also mine\n", lane_ui_patch_block(NEW_ROW))).unwrap();

        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Unchanged);
        assert_eq!(next, None);
        // Content untouched, byte for byte.
        assert_eq!(
            std::fs::read_to_string(&file).unwrap(),
            format!("# mine\n{}\n# also mine\n", lane_ui_patch_block(NEW_ROW))
        );
    }

    #[test]
    fn patch_row_updates_the_block_in_place_and_keeps_user_content() {
        let dir = tempfile::tempdir().unwrap();
        let profile = dir.path().join("web");
        std::fs::create_dir_all(&profile).unwrap();
        let file = profile.join(PROFILE_PATCH_FILENAME);
        std::fs::write(
            &file,
            format!("before\n{}\nafter\n", lane_ui_patch_block(OLD_ROW)),
        )
        .unwrap();

        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Updated);
        assert_eq!(
            next.unwrap(),
            format!("before\n{}\nafter\n", lane_ui_patch_block(NEW_ROW))
        );

        assert_eq!(write_lane_ui_patch_row(&profile, NEW_ROW).unwrap(), PatchOutcome::Updated);
        assert_eq!(
            std::fs::read_to_string(&file).unwrap(),
            format!("before\n{}\nafter\n", lane_ui_patch_block(NEW_ROW))
        );
    }

    #[test]
    fn patch_row_errors_on_an_opening_marker_without_its_closing_marker() {
        let dir = tempfile::tempdir().unwrap();
        let profile = dir.path().join("web");
        std::fs::create_dir_all(&profile).unwrap();
        let file = profile.join(PROFILE_PATCH_FILENAME);
        std::fs::write(&file, format!("{}\nuser row: kept", LANE_UI_BLOCK_BEGIN)).unwrap();

        let error = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap_err();
        let text = error.to_string();
        assert!(text.contains("opening marker but not its closing marker"), "{text}");
        assert!(text.contains(&file.display().to_string()), "{text}");
    }

    #[test]
    fn patch_row_appends_to_empty_comment_marker_and_plain_list_shapes() {
        let dir = tempfile::tempdir().unwrap();
        let block = lane_ui_patch_block(NEW_ROW);

        // Missing file behaves like an empty one.
        let profile = dir.path().join("absent");
        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Added);
        assert_eq!(next.unwrap(), format!("{block}\n"));

        // Truly empty file: separator "".
        let profile = dir.path().join("empty");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join(PROFILE_PATCH_FILENAME), "").unwrap();
        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Added);
        assert_eq!(next.unwrap(), format!("{block}\n"));

        // Comment-only file ending in a single newline: separator "\n".
        let profile = dir.path().join("comments");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join(PROFILE_PATCH_FILENAME), "# hello\n").unwrap();
        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Added);
        assert_eq!(next.unwrap(), format!("# hello\n\n{block}\n"));

        // A `---` document marker is not meaningful content: separator "\n".
        let profile = dir.path().join("marker");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join(PROFILE_PATCH_FILENAME), "---\n").unwrap();
        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Added);
        assert_eq!(next.unwrap(), format!("---\n\n{block}\n"));

        // Plain block sequence without a trailing newline: separator "\n\n".
        let profile = dir.path().join("sequence");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join(PROFILE_PATCH_FILENAME), "- keep: yes").unwrap();
        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Added);
        assert_eq!(next.unwrap(), format!("- keep: yes\n\n{block}\n"));
    }

    #[test]
    fn patch_row_replaces_a_flow_empty_list() {
        let dir = tempfile::tempdir().unwrap();
        let block = lane_ui_patch_block(NEW_ROW);
        let profile = dir.path().join("flow");
        std::fs::create_dir_all(&profile).unwrap();
        std::fs::write(profile.join(PROFILE_PATCH_FILENAME), "[]\n").unwrap();

        let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(outcome, PatchOutcome::Added);
        // The `[]` lines are REMOVED, then the block joins on.
        assert_eq!(next.unwrap(), format!("{block}\n"));

        // A leading comment survives the `[]` removal.
        std::fs::write(profile.join(PROFILE_PATCH_FILENAME), "# c\n[]\n").unwrap();
        let (_, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
        assert_eq!(next.unwrap(), format!("# c\n\n{block}\n"));
    }

    #[test]
    fn patch_row_skips_any_other_shape_without_writing() {
        let dir = tempfile::tempdir().unwrap();
        let shapes = ["{flow: map}\n", "[ ]\n", "scalar\n", "[] # trailing comment\n"];
        for (index, shape) in shapes.iter().enumerate() {
            let profile = dir.path().join(format!("shape-{index}"));
            std::fs::create_dir_all(&profile).unwrap();
            let file = profile.join(PROFILE_PATCH_FILENAME);
            std::fs::write(&file, shape).unwrap();

            let (outcome, next) = compute_lane_ui_patch_row(&profile, NEW_ROW).unwrap();
            assert_eq!(outcome, PatchOutcome::Skipped, "shape {shape:?}");
            assert_eq!(next, None);
            assert_eq!(
                std::fs::read_to_string(&file).unwrap(),
                *shape,
                "a skipped file is never written"
            );
        }
    }

    #[test]
    fn is_skipped_never_copies_build_or_local_files() {
        for name in ["node_modules", "package-lock.json", "settings.local.json", ".git", ".env"] {
            assert!(is_skipped(name), "{name}");
        }
        for name in ["preset.yml", "src", "lib", "client.js"] {
            assert!(!is_skipped(name), "{name}");
        }
    }

    // -- plan / execute -------------------------------------------------------------

    /// Fake DSH home with a `web` profile (wins) and an `editor` profile,
    /// both carrying profile files, plus the package closure.
    fn install_fixture(dir: &Path) -> (PathBuf, PathBuf) {
        let user_home = dir.join("user-home");
        let home = fake_home_with_packages(dir);
        std::fs::create_dir_all(home.join("profiles").join("web")).unwrap();
        std::fs::write(
            home.join("profiles").join("web").join("cordis.patch.yml"),
            "# mine\n- keep: yes\n",
        )
        .unwrap();
        std::fs::create_dir_all(home.join("profiles").join("editor")).unwrap();
        std::fs::write(home.join("profiles").join("editor").join("cordis.yml"), "root: y\n").unwrap();
        let _ = user_home;
        (user_home, home)
    }

    #[test]
    fn plan_previews_the_files_and_the_managed_block() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        assert!(
            source_root.join("agents/backends/dsh/lanes.json").exists(),
            "tests run against the repo's agents/ tree"
        );
        let (_user_home, home) = install_fixture(dir.path());
        let specifiers =
            dsh_deps::resolve_lane_dependencies_in(&home, &lane_plugin_dep_map(), "", None).unwrap();

        let outcome =
            plan_dsh_in(&source_root, &selection(false), &specifiers, &home).unwrap();
        assert_eq!(outcome.created, 9, "nine preset files: {outcome:?}");
        assert_eq!(outcome.skipped, 0);
        assert_eq!(outcome.overwritten, 0);
        assert_eq!(outcome.managed_blocks, 1);
        assert_eq!(outcome.items.len(), 10);
        assert!(outcome.items.iter().all(|item| item.target == Target::Dsh));
        assert_eq!(outcome.items[0].kind, PlanKind::Create);
        assert_eq!(outcome.items[0].source_rel, "agents/backends/dsh/preset.yml");
        let managed = outcome
            .items
            .iter()
            .find(|item| item.kind == PlanKind::ManagedBlock)
            .expect("one managed block item");
        assert_eq!(
            managed.path,
            home.join("profiles").join("web").join(PROFILE_PATCH_FILENAME)
        );
        assert_eq!(managed.source_rel, "profiles/web/cordis.patch.yml");
        assert_eq!(
            outcome.notes,
            vec!["DSH 在会话启动时读取预设：请打开新会话并选择该预设"]
        );

        // Existing files without force plan as skips; the unchanged block plans as a note.
        std::fs::create_dir_all(preset_root(&home)).unwrap();
        std::fs::write(preset_root(&home).join("preset.yml"), "stale").unwrap();
        let second = plan_dsh_in(&source_root, &selection(false), &specifiers, &home).unwrap();
        assert_eq!(second.created, 8);
        assert_eq!(second.skipped, 1);
        assert_eq!(
            second.items[0].kind,
            PlanKind::Skip,
            "preset.yml exists and force is off"
        );

        // With force, the one existing file plans as an overwrite.
        let forced = plan_dsh_in(&source_root, &selection(true), &specifiers, &home).unwrap();
        assert_eq!(forced.overwritten, 1);
        assert_eq!(forced.created, 8);
        assert_eq!(forced.skipped, 0);
    }

    #[test]
    fn execute_installs_preset_plugin_and_the_web_profile_row() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        let (_user_home, home) = install_fixture(dir.path());
        let user_home = dir.path().join("user-home");
        let ctx = engine_context(&user_home);
        let sink = VecSink::default();

        let outcome =
            execute_dsh_in(&source_root, &ctx, &selection(false), &sink, &home, "", None).unwrap();
        assert_eq!(outcome.created, 9);
        assert_eq!(outcome.skipped, 0);
        assert_eq!(outcome.overwritten, 0);
        assert_eq!(outcome.managed_blocks, 1);

        let preset = preset_root(&home);
        // Byte copies.
        assert_eq!(
            std::fs::read(preset.join("preset.yml")).unwrap(),
            std::fs::read(source_root.join("agents/backends/dsh/preset.yml")).unwrap()
        );
        assert_eq!(
            std::fs::read(preset.join("lane-plugin/package.json")).unwrap(),
            std::fs::read(
                source_root.join("agents/backends/dsh/lane-plugin/host-package/package.json")
            )
            .unwrap()
        );
        assert_eq!(
            std::fs::read(preset.join("lane-plugin-ui/package.json")).unwrap(),
            std::fs::read(source_root.join("agents/backends/dsh/lane-plugin-ui/package.json"))
                .unwrap()
        );
        assert_eq!(
            std::fs::read(preset.join("lane-plugin-ui/src/index.js")).unwrap(),
            std::fs::read(source_root.join("agents/backends/dsh/lane-plugin-ui/src/index.js"))
                .unwrap()
        );

        // Rendered files byte-match the render functions' output.
        let lanes = lanes(&source_root).unwrap();
        let specifiers =
            dsh_deps::resolve_lane_dependencies_in(&home, &lane_plugin_dep_map(), "", None).unwrap();
        assert_eq!(
            std::fs::read_to_string(preset.join("agent.cordis.yml")).unwrap(),
            render::render_dsh_composition(&source_root).unwrap()
        );
        assert_eq!(
            std::fs::read_to_string(preset.join("lane-plugin/src/index.js")).unwrap(),
            render::render_lane_host(&source_root, &specifiers).unwrap()
        );
        assert_eq!(
            std::fs::read_to_string(preset.join("lane-plugin/src/roster.generated.js")).unwrap(),
            render::lane_roster_source(&lanes)
        );
        assert_eq!(
            std::fs::read_to_string(preset.join("lane-plugin/src/prompts.generated.js")).unwrap(),
            render::render_lane_prompts(&source_root, &lanes).unwrap()
        );
        let client =
            std::fs::read_to_string(preset.join("lane-plugin-ui/lib/client.js")).unwrap();
        assert_eq!(client, render::lane_ui_client_source(&source_root, &lanes).unwrap());
        assert!(!client.contains("__MY_WORKBENCH_LANES__"));

        let host = std::fs::read_to_string(preset.join("lane-plugin/src/index.js")).unwrap();
        // The two real placeholders are baked; the doc comment's `{{dep:…}}`
        // (an ellipsis, never matched by DEP_RE) legitimately survives, exactly
        // like the CLI's rendered host.
        assert!(!host.contains("{{dep:dsh-tools}}"));
        assert!(!host.contains("{{dep:schemastery}}"));

        // The web profile won and kept its user content.
        let patch =
            std::fs::read_to_string(home.join("profiles/web/cordis.patch.yml")).unwrap();
        assert!(patch.starts_with("# mine\n- keep: yes\n\n"));
        assert!(patch.contains(LANE_UI_BLOCK_BEGIN));
        assert!(patch.contains(LANE_UI_BLOCK_END));
        let row = lane_ui_row_name(&preset);
        assert!(patch.contains(&format!("      name: '{row}'")));
        // The losing profile was never touched.
        assert!(!home.join("profiles/editor/cordis.patch.yml").exists());

        // A second run is idempotent: everything skips, the block is unchanged.
        let second = execute_dsh_in(
            &source_root,
            &ctx,
            &selection(false),
            &VecSink::default(),
            &home,
            "",
            None,
        )
        .unwrap();
        assert_eq!(second.created, 0);
        assert_eq!(second.skipped, 9);
        assert_eq!(second.overwritten, 0);
        assert_eq!(second.managed_blocks, 0);
    }

    #[test]
    fn execute_without_a_single_profile_installs_the_preset_but_mounts_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        let home = fake_home_with_packages(dir.path());
        std::fs::create_dir_all(home.join("profiles").join("alpha")).unwrap();
        std::fs::write(home.join("profiles").join("alpha").join("cordis.yml"), "").unwrap();
        std::fs::create_dir_all(home.join("profiles").join("beta")).unwrap();
        std::fs::write(home.join("profiles").join("beta").join("cordis.yml"), "").unwrap();

        let user_home = dir.path().join("user-home");
        let ctx = engine_context(&user_home);
        let sink = VecSink::default();
        let outcome =
            execute_dsh_in(&source_root, &ctx, &selection(false), &sink, &home, "", None).unwrap();
        assert_eq!(outcome.created, 9);
        assert_eq!(outcome.managed_blocks, 0);

        let texts = sink.log_texts();
        assert!(
            texts
                .iter()
                .any(|text| text.contains("唯一 profile 目录")
                    && text.contains("设置页未写入")),
            "{texts:?}"
        );
        assert!(texts.iter().any(|text| text.contains("手动加入")));
        // No patch file anywhere.
        for profile in ["alpha", "beta"] {
            assert!(!home.join("profiles").join(profile).join("cordis.patch.yml").exists());
        }

        // The same home plans with the not-mounted notes.
        let specifiers =
            dsh_deps::resolve_lane_dependencies_in(&home, &lane_plugin_dep_map(), "", None).unwrap();
        let planned = plan_dsh_in(&source_root, &selection(false), &specifiers, &home).unwrap();
        assert_eq!(planned.managed_blocks, 0);
        assert!(
            planned
                .notes
                .iter()
                .any(|note| note.contains("唯一 profile 目录")),
            "{:?}",
            planned.notes
        );
    }

    #[test]
    fn execute_fails_before_the_first_write_when_dependencies_cannot_resolve() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        // A DSH home with no packages anywhere: resolution fails up front.
        let home = dir.path().join("empty-home");
        std::fs::create_dir_all(home.join("profiles").join("web")).unwrap();

        let user_home = dir.path().join("user-home");
        let ctx = engine_context(&user_home);
        let error = execute_dsh_in(
            &source_root,
            &ctx,
            &selection(false),
            &VecSink::default(),
            &home,
            "",
            None,
        )
        .unwrap_err();
        assert!(
            error
                .to_string()
                .contains("cannot resolve '@deepseek-ai/dsh-tools'"),
            "{error}"
        );
        assert!(!preset_root(&home).exists(), "nothing half-installed");
    }

    #[test]
    fn execute_stops_between_files_when_cancelled() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        let (_user_home, home) = install_fixture(dir.path());
        let user_home = dir.path().join("user-home");
        let ctx = engine_context(&user_home);
        // The header log plus the first file's log flip the sink to cancelled;
        // the second file must never be written.
        let sink = CancelAfterSink::new(2);

        let outcome =
            execute_dsh_in(&source_root, &ctx, &selection(false), &sink, &home, "", None).unwrap();
        assert_eq!(outcome.created, 1, "only preset.yml landed: {outcome:?}");
        assert!(preset_root(&home).join("preset.yml").exists());
        assert!(!preset_root(&home).join("agent.cordis.yml").exists());
        assert_eq!(outcome.managed_blocks, 0);
        // The profile patch layer keeps its original bytes — the row never landed.
        assert_eq!(
            std::fs::read_to_string(home.join("profiles/web/cordis.patch.yml")).unwrap(),
            "# mine\n- keep: yes\n"
        );
    }

    // -- drift ----------------------------------------------------------------

    #[test]
    fn drift_dsh_reports_no_drift_for_an_untouched_install_and_flags_a_tampered_file() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        let (_user_home, home) = install_fixture(dir.path());
        let user_home = dir.path().join("user-home");
        let ctx = engine_context(&user_home);
        execute_dsh_in(
            &source_root,
            &ctx,
            &selection(false),
            &VecSink::default(),
            &home,
            "",
            None,
        )
        .unwrap();

        // Untouched install: all nine preset files and the current managed
        // block match — no drift, and everything was examined.
        let (clean, compared) = drift_dsh_with_compared(&source_root, &home, false).unwrap();
        assert!(clean.is_empty(), "{clean:?}");
        assert!(compared >= 9, "installed preset files are compared: {compared}");

        // Tamper one installed preset file → exactly that drift entry.
        let preset_yml = preset_root(&home).join("preset.yml");
        std::fs::write(&preset_yml, b"tampered\n").unwrap();
        let drifted = drift_dsh(&source_root, &home, false).unwrap();
        assert_eq!(drifted.len(), 1, "{drifted:?}");
        assert_eq!(drifted[0].path, preset_yml);
        assert_eq!(drifted[0].target, Target::Dsh);
        assert_eq!(drifted[0].source_rel, "agents/backends/dsh/preset.yml");

        // Force does not change drift detection (drift = content difference).
        let forced = drift_dsh(&source_root, &home, true).unwrap();
        assert_eq!(forced.len(), 1, "{forced:?}");
        assert_eq!(forced[0].path, preset_yml);
    }

    #[test]
    fn drift_dsh_flags_a_managed_block_the_install_would_rewrite_or_readd() {
        let dir = tempfile::tempdir().unwrap();
        let source_root = repo_root();
        let (_user_home, home) = install_fixture(dir.path());
        let user_home = dir.path().join("user-home");
        let ctx = engine_context(&user_home);
        execute_dsh_in(
            &source_root,
            &ctx,
            &selection(false),
            &VecSink::default(),
            &home,
            "",
            None,
        )
        .unwrap();
        let patch = home.join("profiles").join("web").join(PROFILE_PATCH_FILENAME);

        // Rewriting the row's name inside the managed block is drift the next
        // install would repair, attributed to the patch file with the stable
        // managed-block marker.
        let text = std::fs::read_to_string(&patch).unwrap();
        std::fs::write(&patch, text.replace("      name: '", "      name: 'x")).unwrap();
        let drifted = drift_dsh(&source_root, &home, false).unwrap();
        assert_eq!(drifted.len(), 1, "{drifted:?}");
        assert_eq!(drifted[0].path, patch);
        assert_eq!(drifted[0].target, Target::Dsh);
        assert_eq!(drifted[0].source_rel, MANAGED_PATCH_DRIFT_REL);

        // Deleting the patch file entirely: the install would re-add the row.
        // `web` keeps its cordis.yml so it stays the chosen profile.
        std::fs::write(home.join("profiles").join("web").join("cordis.yml"), "root: y\n").unwrap();
        std::fs::remove_file(&patch).unwrap();
        let drifted = drift_dsh(&source_root, &home, false).unwrap();
        assert_eq!(drifted.len(), 1, "{drifted:?}");
        assert_eq!(drifted[0].path, patch);
        assert_eq!(drifted[0].source_rel, MANAGED_PATCH_DRIFT_REL);
    }
}
